Repository mehta-lab/recOrder, pull requests merged in 2022-10, with the labels that each got.

#198 fixing the issue to connect and reconnect to MM
  recOrder/plugin/widget/main_widget.py
Labels: bug

#215 Recommend MM 2022-09-20
  docs/microscope-installation-guide.md
  recOrder/plugin/widget/main_widget.py
Labels: enhancement

#227 Remove microscope parameters from calibration metadata
  recOrder/calib/Calibration.py
  recOrder/io/metadata_reader.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/calibration_workers.py
Labels: enhancement

#219 0.2.0 integration PR
  docs/images/create_group_voltage.png
  docs/images/create_preset_voltage.png
  docs/images/recOrder_Fig1_Overview.png
  docs/microscope-installation-guide.md
  recOrder/calib/Calibration.py
  recOrder/io/metadata_reader.py
  recOrder/io/utils.py
  recOrder/plugin/config_offline_default.yml
  recOrder/plugin/qtdesigner/recOrder_ui.py
  recOrder/plugin/qtdesigner/recOrder_ui.ui
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/calibration_workers.py
  recOrder/plugin/workers/reconstruction_workers.py
  recOrder/scripts/repeat-cal-acq-rec.py
  recOrder/scripts/repeat-calibration.py
Labels: bug, enhancement

#228 Block `imageio` versions that cause import error
  setup.cfg
Labels: bug

#229 Introduce Black formatting into the code base
  .git-blame-ignore-revs
  docs/development-guide.md
  recOrder/__init__.py
  recOrder/acq/acq_functions.py
  recOrder/calib/Calibration.py
  recOrder/calib/Optimization.py
  recOrder/compute/__init__.py
  recOrder/compute/qlipp_compute.py
  recOrder/io/__init__.py
  recOrder/io/_reader.py
  recOrder/io/config_reader.py
  recOrder/io/core_functions.py
  recOrder/io/metadata_reader.py
  recOrder/io/utils.py
  recOrder/io/zarr_converter.py
  recOrder/pipelines/base.py
  recOrder/pipelines/phase_from_bf_pipeline.py
  recOrder/pipelines/pipeline_manager.py
  recOrder/pipelines/qlipp_pipeline.py
  recOrder/plugin/__init__.py
  recOrder/plugin/qtdesigner/mplwidget.py
  recOrder/plugin/widget/loading_widget.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/widget/napari_plugin_entry_point.py
  recOrder/plugin/workers/acquisition_workers.py
  recOrder/plugin/workers/calibration_workers.py
  recOrder/plugin/workers/reconstruction_workers.py
  recOrder/scripts/cli.py
  recOrder/scripts/launch_napari.py
  recOrder/scripts/md5_check_sum.py
  recOrder/scripts/repeat-cal-acq-rec.py
  recOrder/scripts/repeat-calibration.py
  recOrder/tests/calibration_tests/test_calibration.py
  recOrder/tests/config_reader_tests/test_config_reader.py
  recOrder/tests/conftest.py
  recOrder/tests/converter_tests/test_converter.py
  recOrder/tests/pipeline_tests/test_old_processing.py
  recOrder/tests/pipeline_tests/test_phase_from_bf_pipeline.py
  recOrder/tests/pipeline_tests/test_qlipp_pipeline.py
  recOrder/tests/pipeline_tests/test_qlipp_pipeline_tiff.py
  recOrder/tests/reader_tests/test_reader.py
Labels: enhancement, meta

#239 Test MM Core calls with mocks
  recOrder/tests/mmcore_tests/test_core_func.py
Labels: enhancement, testing
