Repository mehta-lab/recOrder, pull requests merged in 2022-09, with the labels that each got.

#162 Check for equal exposures across channels
  recOrder/plugin/workers/acquisition_workers.py
Labels: bug, enhancement

#167 Fix background correction for non-square images and online mode
  recOrder/io/utils.py
  recOrder/pipelines/qlipp_pipeline.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/acquisition_workers.py
Labels: bug

#160 Update shutter behavior and LF acquisition channel order
  .github/workflows/pytests.yml
  .github/workflows/test_and_deploy.yml
  README.md
  docs/microscope-installation-guide.md
  docs/software-installation-guide.md
  recOrder/acq/acq_functions.py
  recOrder/calib/Calibration.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/acquisition_workers.py
  recOrder/plugin/workers/calibration_workers.py
  setup.cfg
  tox.ini
Labels: enhancement

#157 Print RAM warning message in online and offline modes
  recOrder/io/utils.py
  recOrder/pipelines/pipeline_manager.py
  recOrder/plugin/workers/acquisition_workers.py
Labels: bug, enhancement

#169 Remove background averaging
  recOrder/io/utils.py
  recOrder/pipelines/qlipp_pipeline.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/acquisition_workers.py
Labels: bug

#174 Show RAM warning in GUI / log in CLI
  recOrder/io/utils.py
  recOrder/pipelines/pipeline_manager.py
  recOrder/plugin/workers/acquisition_workers.py
Labels: enhancement

#178 `Capture Background` without calibration yields a warning
  recOrder/plugin/widget/main_widget.py
Labels: enhancement

#184 Initialize calibration values when loading from metadata files
  recOrder/plugin/workers/calibration_workers.py
Labels: bug

#183 Upgrade `pycromanager` and `micromanager`
  docs/microscope-installation-guide.md
  recOrder/plugin/widget/main_widget.py
  setup.cfg
Labels: enhancement

#185 Development guide
  docs/README.md
  docs/development-guide.md
Labels: documentation

#165 OSX_arm64 dev install and Markdown linting
  README.md
  docs/development-guide.md
  docs/software-installation-guide.md
Labels: documentation

#195 Refactor calibration workers and fix metadata writing
  recOrder/io/metadata_reader.py
  recOrder/plugin/workers/calibration_workers.py
Labels: bug, enhancement

#196 Mapping capture background path from calibration to reconstruction
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/calibration_workers.py
Labels: enhancement

#206 Hide "Use Cropped ROI" checkbox
  recOrder/plugin/widget/main_widget.py
Labels: enhancement

#202 Remove pre-acquisition background file check for 'Estimated' background correction
  recOrder/plugin/widget/main_widget.py
Labels: bug

#208 Add "pad_z" when constructing microscope metadata
  recOrder/plugin/widget/main_widget.py
Labels: bug

#199 Plot calibrated LC states
  recOrder/calib/Calibration.py
  recOrder/plugin/widget/main_widget.py
  recOrder/plugin/workers/calibration_workers.py
Labels: enhancement

#209 Save background reconstruction and visualization
  recOrder/plugin/workers/calibration_workers.py
Labels: enhancement
