Repository mehta-lab/recOrder, pull requests merged in 2022-11, with the labels that each got.

#251 Bump napari-hub-preview-action version to fix CI
  .github/workflows/plugin_preview.yml
Labels: bug

#248 90 degree orientation offset checkbox
  recOrder/acq/acquisition_workers.py
  recOrder/calib/calibration_workers.py
  recOrder/plugin/gui.py
  recOrder/plugin/gui.ui
  recOrder/plugin/main_widget.py
Labels: enhancement

#252 Import `qtpy` instead of `PyQt5` in autogenerated `gui.py`
  docs/development-guide.md
  recOrder/plugin/gui.py
Labels: bug, documentation

#249 Reconstruction scripts w/ documentation
  docs/README.md
  docs/images/FlowChart.png
  docs/images/acq_finished.png
  docs/images/connect_to_mm.png
  docs/images/create_preset_voltage.png
  docs/images/flowchart_resize.jpg
  docs/images/flowchart_resize.png
  docs/images/recOrder_Fig1_Overview.png
  docs/images/recOrder_logo.jpg
  docs/images/recOrder_logo.png
  docs/images/recOrder_logo_web.jpg
  docs/images/recOrder_logo_web.png
  docs/images/recOrder_offline.png
  docs/images/reconstruct_acq.png
  docs/images/reconstruct_acq2.png
  docs/images/reconstruct_acq_general.png
  docs/images/reconstruct_acq_mparams.png
  docs/images/reconstruct_acq_reg.png
  docs/images/switch_online.png
  docs/napari-plugin-guide.md
  docs/reconstruction-guide.md
  examples/__init__.py
  examples/notebooks/QLIPP_Calibration_Notebook.ipynb
  examples/notebooks/Reconstruction_PhaseFromBF.ipynb
  examples/notebooks/Reconstruction_QLIPP.ipynb
  examples/recon-phase-from-bf.py
  examples/recon-qlipp.py
  recOrder/compute/qlipp_compute.py
Labels: documentation, work-around

#256 Override initial tab to focus on 'LC Calibration'
  recOrder/plugin/main_widget.py
Labels: bug

#260 Rename acquisition buttons and move "Phase from BF" checkbox to its own button
  recOrder/plugin/gui.py
  recOrder/plugin/gui.ui
  recOrder/plugin/main_widget.py
  recOrder/scripts/repeat-cal-acq-rec.py
Labels: enhancement

#264 Move the most recent layer to the top of the layers list
  recOrder/plugin/main_widget.py
Labels: enhancement

#269 Use HSV colormap for the background orientation layer
  recOrder/plugin/main_widget.py
Labels: enhancement

#270 Draw overlay for both 2D and 3D birefringence acquisitions
  recOrder/plugin/main_widget.py
Labels: bug

#273 Read illumination parameters from the loaded calibration instead of GUI during acquisition
  recOrder/acq/acquisition_workers.py
  recOrder/calib/calibration_workers.py
  recOrder/plugin/main_widget.py
Labels: bug

#275 Add ROI size check for the previous phase reconstructor
  recOrder/acq/acquisition_workers.py
  recOrder/plugin/main_widget.py
Labels: bug

#284 Add 3D->2D phase script and add `in_focus_slice` argument
  examples/3D-bf-to-2D-phase.py
  examples/3D-bf-to-3D-phase.py
  examples/README.md
  examples/recon-qlipp.py
  recOrder/compute/qlipp_compute.py
Labels: enhancement
