Repository mehta-lab/recOrder, pull requests merged in 2023-06, with the labels that each got.

#346 Test docking the plugin widget
  .github/workflows/pytests.yml
  .github/workflows/test_and_deploy.yml
  recOrder/acq/acquisition_workers.py
  recOrder/calib/calibration_workers.py
  recOrder/plugin/main_widget.py
  recOrder/tests/widget_tests/test_dock_widget.py
  setup.cfg
  tox.ini
Labels: testing

#359 Multiple birefringence overlays
  recOrder/plugin/main_widget.py
  recOrder/tests/util_tests/test_overlays.py
Labels: enhancement

#377 Refactor and test compute transfer function
  recOrder/cli/compute_transfer_function.py
  recOrder/tests/cli_tests/test_cli.py
  recOrder/tests/conftest.py
Labels: enhancement, good first issue, testing
