Repository mehta-lab/recOrder, pull requests merged in 2023-08, with the labels that each got.

#391 Bump dependencies and enable widget test
  recOrder/tests/widget_tests/test_dock_widget.py
  setup.cfg
Labels: testing, maintenance

#394 0.3.1 documentation patch
  docs/microscope-installation-guide.md
Labels: documentation

#395 0.4.0 installation documentation
  docs/development-guide.md
  docs/microscope-installation-guide.md
Labels: documentation

#423 Simplify Dask graph before computing overlay
  recOrder/plugin/main_widget.py
Labels: bug, upstream
