Repository mehta-lab/recOrder, pull requests merged in 2024-07, with the labels that each got.

#475 Pin ome-zarr
  setup.cfg
Labels: maintenance, upstream

#469 Fix background-check bug
  recOrder/cli/apply_inverse_transfer_function.py
Labels: bug

#478 Bump Python, iohub, and waveorder
  .github/workflows/pytests.yml
  .github/workflows/test_and_deploy.yml
  recOrder/cli/apply_inverse_models.py
  recOrder/cli/settings.py
  recOrder/tests/cli_tests/test_settings.py
  setup.cfg
  tox.ini
Labels: maintenance
